#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Setup global OpenMemory commands in PowerShell profile

.DESCRIPTION
    This script adds OpenMemory commands (openmemory-init, start-openmemory, stop-openmemory)
    to your PowerShell profile so they can be run from any directory.

.PARAMETER Force
    Skip confirmation prompts and force update if already configured

.EXAMPLE
    .\setup-global-commands.ps1
    Add OpenMemory commands to PowerShell profile

.EXAMPLE
    .\setup-global-commands.ps1 -Force
    Force update the configuration without prompts
#>

param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "OpenMemory-Code Global Commands Setup" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host ""

# Get the OpenMemory-Code installation directory
$OpenMemoryDir = Split-Path -Parent $PSCommandPath

# Get PowerShell profile path
$ProfilePath = $PROFILE.CurrentUserAllHosts
if (-not $ProfilePath) {
    $ProfilePath = "$env:USERPROFILE\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
}

Write-Host "OpenMemory-Code location: $OpenMemoryDir" -ForegroundColor Green
Write-Host "PowerShell profile: $ProfilePath" -ForegroundColor Green
Write-Host ""

# Create profile directory if it doesn't exist
$ProfileDir = Split-Path -Parent $ProfilePath
if (-not (Test-Path $ProfileDir)) {
    Write-Host "Creating profile directory: $ProfileDir" -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $ProfileDir -Force | Out-Null
}

# Create profile file if it doesn't exist
if (-not (Test-Path $ProfilePath)) {
    Write-Host "Creating PowerShell profile: $ProfilePath" -ForegroundColor Yellow
    New-Item -ItemType File -Path $ProfilePath -Force | Out-Null
}

# Read existing profile content
$profileContent = Get-Content -Path $ProfilePath -Raw -ErrorAction SilentlyContinue
if (-not $profileContent) {
    $profileContent = ""
}

# Check if OpenMemory commands are already configured
if ($profileContent -match "# OpenMemory-Code Global Commands") {
    if (-not $Force) {
        Write-Host "OpenMemory commands are already configured in your profile!" -ForegroundColor Yellow
        $response = Read-Host "Do you want to update the configuration? (y/N)"
        if ($response -ne "y" -and $response -ne "Y") {
            Write-Host "Skipping setup." -ForegroundColor Yellow
            exit 0
        }
    } else {
        Write-Host "Updating existing OpenMemory configuration..." -ForegroundColor Yellow
    }

    # Remove old configuration
    $profileContent = $profileContent -replace "(?ms)# OpenMemory-Code Global Commands - START.*?# OpenMemory-Code Global Commands - END\r?\n?", ""
}

# Add OpenMemory commands to profile
$openMemoryConfig = @"

# OpenMemory-Code Global Commands - START
# Auto-generated by setup-global-commands.ps1
`$global:OPENMEMORY_CODE_DIR = "$OpenMemoryDir"

function openmemory-init {
    param([Parameter(Position = 0)][string]`$ProjectPath = `$PWD.Path)
    & "`$global:OPENMEMORY_CODE_DIR\openmemory-init.ps1" `$ProjectPath
}

function start-openmemory {
    param([switch]`$Dev, [switch]`$Verbose, [switch]`$SkipLogging)
    Push-Location `$global:OPENMEMORY_CODE_DIR
    try {
        & ".\start-openmemory.ps1" -Dev:`$Dev -Verbose:`$Verbose -SkipLogging:`$SkipLogging
    } finally {
        Pop-Location
    }
}

function stop-openmemory {
    Push-Location `$global:OPENMEMORY_CODE_DIR
    try {
        & ".\stop-openmemory.ps1"
    } finally {
        Pop-Location
    }
}

Write-Host "OpenMemory-Code commands loaded (openmemory-init, start-openmemory, stop-openmemory)" -ForegroundColor DarkGray
# OpenMemory-Code Global Commands - END

"@

# Append to profile
$newProfileContent = $profileContent.TrimEnd() + $openMemoryConfig
Set-Content -Path $ProfilePath -Value $newProfileContent -NoNewline

Write-Host ""
Write-Host "SUCCESS! Global commands have been added to your PowerShell profile" -ForegroundColor Green
Write-Host ""
Write-Host "Available commands:" -ForegroundColor Cyan
Write-Host "  • openmemory-init [project-path]  - Initialize a project for OpenMemory" -ForegroundColor White
Write-Host "  • start-openmemory [-Dev]         - Start OpenMemory services" -ForegroundColor White
Write-Host "  • stop-openmemory                 - Stop OpenMemory services" -ForegroundColor White
Write-Host ""
Write-Host "To use the commands:" -ForegroundColor Yellow
Write-Host "  1. Close and reopen your PowerShell terminal" -ForegroundColor White
Write-Host "  2. Or run: . `"$ProfilePath`"" -ForegroundColor White
Write-Host ""
Write-Host "Then you can run 'openmemory-init' from any directory!" -ForegroundColor Green
Write-Host ""
